name: arctic-cnn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - xarray
  - netcdf4          # xarray backend for reading .nc files
  - matplotlib
  - scipy
  - scikit-learn
  - tensorflow
  - pip
