name: analysis_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - scipy
  - scikit-learn
  - tensorflow 
  - cartopy
  - xesmf
  - gcsfs
  - cdsapi
  - requests
  - pip
